language: objective-c
osx_image: xcode8.2
xcode_workspace: Meizi.xcworkspace
xcode_scheme: Meizi
before_install:
- gem install activesupport -v 4.2.6
- gem update cocoapods
- pod repo update --silent
- pod install
script: xcodebuild -workspace Meizi.xcworkspace -scheme Meizi CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
